---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: openfaas-gateway
  namespace: openfaas
spec:
  tls:
  - hosts:
    - gw.secure-faas.com
    secretName: tls-secret
  rules:
  - host: gw.secure-faas.com
    http:
      paths:
      - backend:
          serviceName: gateway
          servicePort: 8080
