provider:
  name: faas

functions:
  unprotected-haveibeenpwned:
    lang: go
    handler: ./haveibeenpwned
    image: functions/haveibeenpwned:0.13.0
  protected-haveibeenpwned:
    lang: go
    handler: ./haveibeenpwned
    image: functions/haveibeenpwned:0.13.0
